### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by ProPlayer478** [henry-richard7/Grand-Theft-Auto-Online-IP-Grabber#1]
Hello can you tell me the passage needed to run this ip grabber? thanks very much

**Comment by henry-richard7** [comment]
Hi,
 You need to install this driver first before using the program https://www.winpcap.org/ and the download the release [Frome Here](https://github.com/henry-richard7/Grand-Theft-Auto-Online-IP-Grabber/releases) extract and open the exe file and launch GTA V your done.

**Comment by ProPlayer478** [comment]
Hi i can't download winpcap but i managed to download npcap, is that okay?

**Comment by henry-richard7** [comment]
I have not tested the program with npcap... you can check out?

**Comment by ProPlayer478** [comment]
No, with npcap dont work, another question, this program can work with gta 5 online on xbox?

**Comment by henry-richard7** [comment]
No Only for PC
