### ISSUE TITLE
Players ID

### ISSUE THREAD

**Issue by ekids9702122935** [henry-richard7/Grand-Theft-Auto-Online-IP-Grabber#3]
Hi, thanks for your sharing of this tool in advance.
I would like to know if you have any tips to point the IP to the players ID? Thanks a lot.

**Comment by henry-richard7** [comment]
Hi,
 Currently you can't pin point IP to a specific player, I am currently working on it and will give an update.

**Comment by ekids9702122935** [comment]
Great!
Looking forward to it.👍
