### ISSUE TITLE
winpcap -> npcap

### ISSUE THREAD

**Issue by HasseM** [henry-richard7/Grand-Theft-Auto-Online-IP-Grabber#5]
Winpcap is not supported anymore and Npcap is the way forward. You may want to update your program to use the Npcap sdk and the docs to point to Npcap.

Also all network devices are listed double for some reason.

Wondering if you have any progress about the content of the udp packets received? Please share your findings. I changed the program to also show the hex contents in the listview and update it when new info comes in. But wow, not a clue about its meaning yet!

**Comment by henry-richard7** [comment]
Hi,
Thanks for the heads up I will update the program.

I will also try to remove the repeated devices.

Well about the UDP packets I don't know about them so I didn't add them in the program.

Thanks for using this program.!

**Comment by henry-richard7** [comment]
I have fixed the repeated interface issue! and also NPcap is supported. 

You can download it from Release tab.

**Comment by HasseM** [comment]
Great. Maybe also update the readme to point to npcap?

**Comment by henry-richard7** [comment]
Done 👍
